const inquirer = require('inquirer');
const jest = require('jest');
const colors = require('./lib/colors');
const {generateSVG} = require('./lib/generateSVG.js');

function init(){
    const shapes = ['Circle', 'Square', 'Triangle'];
    inquirer
        .prompt([
            { // text in the logo [[ CONSIDER: limiting the amount of characters]]
                type: 'input',
                message: 'Please enter your text (0-3 characters):',
                name: 'text',
                validate: function(input){
                    if(input.length <= 3){
                        return true;
                    } else { 
                        console.log('\nYour input must be 0-3 characters long.');
                        return false; 
                    }
                }
            },
            {// asks for text color
                type: 'input',
                message: 'Text Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'textColor',
                // checks if text input is a valid color
                validate: function(input){
                    if(input.charAt(0) == '#'){ return true; }
                    if (colors.hasOwnProperty(input.toLowerCase().replace(/\s/g, ''))){
                        return true;
                    } else { 
                        console.log(`\n\'${input}\' is not a valid color. Please try again.`);
                        return false; 
                    }
                }
            },
            {// asks the user to select a shape from a predetermined list of shapes (circle, triangle, square)
                type: 'list',
                message: 'Select a desired shape:',
                name: 'shape',
                choices: shapes
            },
            {// asks for shape color
                type: 'input',
                message: 'Shape Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'shapeColor',
                validate: function(input){
                    if(input.charAt(0) == '#'){ return true; }
                    if (colors.hasOwnProperty(input.toLowerCase().replace(/\s/g, ''))){
                        return true;
                    } else { 
                        console.log(`\n\'${input}\' is not a valid color. Please try again.`);
                        return false; 
                    }
                }
            }
        ])
        // decide what to do with the response object generated by .prompt
        .then((response) => {
            generateSVG(response);
        })
        // check for any errors
        .catch((error) => {
            console.log(error);
            console.log('\nAn error has occurred.');
        });
}
init();