const fs = require('fs');
const inquirer = require('inquirer');
const jest = require('jest');

const logoWidth = 300;
const logoHeight = 200;
const logoX = Math.floor(logoWidth/2); //center X | used as midpoint for triangle
const logoY = Math.floor(logoHeight/2); //center Y | used as radius for circle (so it's not too big for its container)

const logoTemplateCircle = 
`<svg width="${logoWidth}" height="${logoHeight}">
    <circle cx="${logoX}" cy="${logoY}" r="${logoY}" fill="yellow" />
</svg>`;
const logoTemplateRectangle = 
`<svg width="${logoWidth}" height="${logoHeight}">
    <rect width="${logoWidth}" height="${logoHeight}" style="fill:rgb(0,0,255)" />
</svg>`;
const {tri1, tri2, tri3} = [`0,${logoHeight}`, `${logoX},0`, `${logoWidth},${logoHeight}`]; //triangle points
const logoTemplateTriangle = 
`<svg width="${logoWidth}" height="${logoHeight}">
    <polygon points="${tri1} ${tri2} ${tri3}" style="fill:lime" />
</svg>`;



function init(){
    const shapes = ['Circle', 'Triangle', 'Square'];
    inquirer
        .prompt([
            { // text in the logo [[ CONSIDER: limiting the amount of characters]]
                type: 'input',
                message: 'Please enter your text:',
                name: 'text'
            },
            {// asks for text color
                type: 'input',
                message: 'Text Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'textColor'
            },
            {// asks the user to select a shape from a predetermined list of shapes (circle, triangle, square)
                type: 'list',
                message: 'Select a desired shape:',
                name: 'shape',
                choices: shapes
            },
            {// asks for shape color
                type: 'input',
                message: 'Shape Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'shapeColor'
            }
        ])
        // decide what to do with the response object generated by .prompt
        .then((response) => {
            console.log(response);
        });
}

init();