const fs = require('fs');
const inquirer = require('inquirer');
const jest = require('jest');

const logoWidth = 300;
const logoHeight = 200;
const logoX = Math.floor(logoWidth/2); //center X | used as midpoint for triangle
const logoY = Math.floor(logoHeight/2); //center Y | used as radius for circle (so it's not too big for its container)




function generateSVG({text, textColor, shape, shapeColor}){
    const logoTemplateText = `<text x="108" y="115" font-size="50" fill="${textColor}">${text}</text>`;
    const logoTemplateCircle = `<svg width="${logoWidth}" height="${logoHeight}"><circle cx="${logoX}" cy="${logoY}" r="${logoY}" fill="${shapeColor}" />${logoTemplateText}</svg>`;
    const logoTemplateRectangle = `<svg width="${logoWidth}" height="${logoHeight}"><rect width="${logoWidth}" height="${logoHeight}" style="fill:${shapeColor}" />${logoTemplateText}</svg>`;
    const {tri1, tri2, tri3} = [`60,150`, `150,20`, `240,150`]; //triangle points
    const logoTemplateTriangle = `<svg width="${logoWidth}" height="${logoHeight}"><polygon points="${tri1} ${tri2} ${tri3}" style="fill:${shapeColor}"/>${logoTemplateText}</svg>`;

    switch(shape){
        case 'Circle':
            console.log(shape);
            break;
        case 'Square':
            console.log(shape);
            break;
        case 'Triangle':
            console.log(shape);
            break;
        default:
            console.log(`A ${shape} is not a shape.`);
            break;
    }

}


function init(){
    const shapes = ['Circle', 'Triangle', 'Square'];
    inquirer
        .prompt([
            { // text in the logo [[ CONSIDER: limiting the amount of characters]]
                type: 'input',
                message: 'Please enter your text:',
                name: 'text'
            },
            {// asks for text color
                type: 'input',
                message: 'Text Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'textColor',
                validate: function(input){

                }
            },
            {// asks the user to select a shape from a predetermined list of shapes (circle, triangle, square)
                type: 'list',
                message: 'Select a desired shape:',
                name: 'shape',
                choices: shapes
            },
            {// asks for shape color
                type: 'input',
                message: 'Shape Color (Keyword: Blue | Hexadecimal: #0000FF):',
                name: 'shapeColor'
            }
        ])
        // decide what to do with the response object generated by .prompt
        .then((response) => {
            generateSVG(response);
            console.log(response);
        });
}

init();